import { NextResponse } from "next/server";
import { supportedLocales } from "@/lib/locales";
import { getBlogPosts } from "@/lib/blogApi";
import { getApps } from "@/lib/appStoreApi";

/**
 * Sitemap Index (Yoast SEO Style)
 *
 * Route: /sitemap_index.xml
 * Displays all sitemaps in a clean, organized format similar to Yoast SEO
 * Shows sitemap URLs with Last Modified dates
 *
 * This is an alternative presentation of the sitemap index
 */

async function getBlogPostsCount(locale: string): Promise<number> {
  try {
    const response = await getBlogPosts({
      page: 1,
      limit: 1,
      locale,
      minimal: true,
    });

    if (response.success && response.data && response.data.pagination) {
      return response.data.pagination.totalPosts || 0;
    }

    return 0;
  } catch (error) {
    return 0;
  }
}

async function getAppsCount(locale: string): Promise<number> {
  try {
    const response = await getApps({
      page: 1,
      limit: 1,
      locale,
      minimal: true,
    });

    if (response.success && response.data && response.data.pagination) {
      const apps = response.data.apps || [];

      // Filter apps: only count apps that have translation for this locale
      const filteredApps = apps.filter((app: any) => {
        if (app.translations && typeof app.translations === "object") {
          const hasTranslation =
            app.translations[locale as keyof typeof app.translations] !==
            undefined;
          if (locale === "en") return true;
          return hasTranslation;
        }
        return true;
      });

      return filteredApps.length;
    }

    return 0;
  } catch (error) {
    return 0;
  }
}

export async function GET() {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://flowxtra.com";
  const locales = supportedLocales;
  const postsPerFile = 100;

  // Build HTML page (Yoast SEO style)
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XML Sitemap Index - Flowxtra</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px 20px;
      background-color: #fff;
    }
    h1 {
      font-size: 32px;
      font-weight: 600;
      color: #1a1a1a;
      margin-bottom: 10px;
    }
    .description {
      color: #666;
      margin-bottom: 30px;
      font-size: 14px;
    }
    .description a {
      color: #d63638;
      text-decoration: none;
    }
    .description a:hover {
      text-decoration: underline;
    }
    .count {
      font-size: 16px;
      color: #555;
      margin-bottom: 30px;
      padding: 15px;
      background-color: #f5f5f5;
      border-radius: 4px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
      background-color: #fff;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    thead {
      background-color: #f8f9fa;
    }
    th {
      text-align: left;
      padding: 15px;
      font-weight: 600;
      color: #1a1a1a;
      border-bottom: 2px solid #e0e0e0;
      font-size: 14px;
    }
    td {
      padding: 15px;
      border-bottom: 1px solid #e0e0e0;
      font-size: 14px;
    }
    tr:hover {
      background-color: #f8f9fa;
    }
    a {
      color: #0073aa;
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
      color: #005177;
    }
    .lastmod {
      color: #666;
      font-size: 13px;
    }
    .section-header {
      font-size: 18px;
      font-weight: 600;
      color: #1a1a1a;
      margin-top: 40px;
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 2px solid #e0e0e0;
    }
  </style>
</head>
<body>
  <h1>XML Sitemap</h1>
  <div class="description">
    Generated by <a href="https://flowxtra.com" target="_blank">Flowxtra</a>, this is an XML Sitemap Index, meant for consumption by search engines.<br>
    You can find more information about XML sitemaps on <a href="https://www.sitemaps.org/" target="_blank">sitemaps.org</a>.
  </div>`;

  // Collect all sitemaps organized by type
  const sitemaps: Array<{
    url: string;
    lastmod: string;
    type: string;
    locale?: string;
  }> = [];

  // Add locale-specific sitemap indexes (main indexes)
  for (const locale of locales) {
    sitemaps.push({
      url: `${baseUrl}/sitemap-${locale}.xml`,
      lastmod: new Date().toISOString(),
      type: "Locale Index",
      locale: locale.toUpperCase(),
    });

    // Add static pages sitemap for this locale
    sitemaps.push({
      url: `${baseUrl}/sitemap-static-${locale}.xml`,
      lastmod: new Date().toISOString(),
      type: "Static Pages",
      locale: locale.toUpperCase(),
    });

    // Add blog sitemaps for this locale (if available)
    const totalPosts = await getBlogPostsCount(locale);
    const totalBlogFiles = Math.ceil(totalPosts / postsPerFile);

    if (totalPosts > 0 && totalBlogFiles > 0) {
      for (let fileIndex = 0; fileIndex < totalBlogFiles; fileIndex++) {
        sitemaps.push({
          url: `${baseUrl}/sitemap-${locale}-blog-${fileIndex}.xml`,
          lastmod: new Date().toISOString(),
          type: "Blog Posts",
          locale: locale.toUpperCase(),
        });
      }
    }

    // Add app-store sitemaps for this locale (if available)
    const totalApps = await getAppsCount(locale);
    const totalAppFiles = Math.ceil(totalApps / postsPerFile);

    if (totalApps > 0 && totalAppFiles > 0) {
      for (let fileIndex = 0; fileIndex < totalAppFiles; fileIndex++) {
        sitemaps.push({
          url: `${baseUrl}/sitemap-${locale}-app-store-${fileIndex}.xml`,
          lastmod: new Date().toISOString(),
          type: "App Store",
          locale: locale.toUpperCase(),
        });
      }
    }
  }

  // Add complete sitemap
  sitemaps.push({
    url: `${baseUrl}/sitemap-all.xml`,
    lastmod: new Date().toISOString(),
    type: "Complete Sitemap",
  });

  // Display count
  html += `
  <div class="count">
    This XML Sitemap Index file contains <strong>${
      sitemaps.length
    }</strong> sitemap${sitemaps.length !== 1 ? "s" : ""}.
  </div>`;

  // Group sitemaps by locale for better organization
  const groupedByLocale: Record<
    string,
    Array<{ url: string; lastmod: string; type: string }>
  > = {};
  const otherSitemaps: Array<{ url: string; lastmod: string; type: string }> =
    [];

  sitemaps.forEach((sitemap) => {
    if (sitemap.locale) {
      if (!groupedByLocale[sitemap.locale]) {
        groupedByLocale[sitemap.locale] = [];
      }
      groupedByLocale[sitemap.locale].push({
        url: sitemap.url,
        lastmod: sitemap.lastmod,
        type: sitemap.type,
      });
    } else {
      otherSitemaps.push({
        url: sitemap.url,
        lastmod: sitemap.lastmod,
        type: sitemap.type,
      });
    }
  });

  // Display table organized by locale
  html += `
  <table>
    <thead>
      <tr>
        <th>Sitemap</th>
        <th>Type</th>
        <th>Last Modified</th>
      </tr>
    </thead>
    <tbody>`;

  // Display sitemaps grouped by locale
  const sortedLocales = Object.keys(groupedByLocale).sort();
  sortedLocales.forEach((locale) => {
    html += `
      <tr style="background-color: #f0f0f0;">
        <td colspan="3" style="font-weight: 600; padding: 20px 15px; border-bottom: 2px solid #ddd;">
          ${locale} - ${groupedByLocale[locale].length} sitemap${
      groupedByLocale[locale].length !== 1 ? "s" : ""
    }
        </td>
      </tr>`;

    groupedByLocale[locale].forEach((sitemap) => {
      const lastModDate = new Date(sitemap.lastmod);
      const formattedDate =
        lastModDate.toISOString().replace("T", " ").substring(0, 19) +
        " +00:00";

      html += `
      <tr>
        <td><a href="${sitemap.url}" target="_blank">${sitemap.url}</a></td>
        <td>${sitemap.type}</td>
        <td class="lastmod">${formattedDate}</td>
      </tr>`;
    });
  });

  // Display other sitemaps (like complete sitemap)
  if (otherSitemaps.length > 0) {
    html += `
      <tr style="background-color: #f0f0f0;">
        <td colspan="3" style="font-weight: 600; padding: 20px 15px; border-bottom: 2px solid #ddd; border-top: 2px solid #ddd;">
          Other Sitemaps
        </td>
      </tr>`;

    otherSitemaps.forEach((sitemap) => {
      const lastModDate = new Date(sitemap.lastmod);
      const formattedDate =
        lastModDate.toISOString().replace("T", " ").substring(0, 19) +
        " +00:00";

      html += `
      <tr>
        <td><a href="${sitemap.url}" target="_blank">${sitemap.url}</a></td>
        <td>${sitemap.type}</td>
        <td class="lastmod">${formattedDate}</td>
      </tr>`;
    });
  }

  html += `
    </tbody>
  </table>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
