import { NextRequest, NextResponse } from "next/server";
import { isSupportedLocale, supportedLocales } from "@/lib/locales";
import { getBlogPosts } from "@/lib/blogApi";
import { getApps } from "@/lib/appStoreApi";

/**
 * Locale-specific Sitemap Index
 *
 * Route format: /sitemap/en.xml, /sitemap/de.xml, etc.
 * Each locale sitemap index contains:
 * 1. Static pages sitemap
 * 2. Blog posts sitemaps (if available)
 * 3. App Store apps sitemaps (if available)
 *
 * Locales are dynamically validated using lib/locales.ts
 */

async function getAppsCount(locale: string): Promise<number> {
  try {
    const response = await getApps({
      page: 1,
      limit: 1,
      locale,
      minimal: true,
    });

    if (response.success && response.data && response.data.pagination) {
      const apps = response.data.apps || [];

      // Filter apps: only count apps that have translation for this locale
      const filteredApps = apps.filter((app: any) => {
        if (app.translations && typeof app.translations === "object") {
          const hasTranslation =
            app.translations[locale as keyof typeof app.translations] !==
            undefined;
          if (locale === "en") return true;
          return hasTranslation;
        }
        return true;
      });

      return filteredApps.length;
    }

    return 0;
  } catch (error) {
    console.warn(
      `⚠️ Error fetching apps count for locale "${locale}":`,
      error instanceof Error ? error.message : String(error)
    );
    return 0;
  }
}

async function getBlogPostsCount(locale: string): Promise<number> {
  try {
    const response = await getBlogPosts({
      page: 1,
      limit: 1,
      locale,
      minimal: true,
    });

    if (response.success && response.data && response.data.pagination) {
      return response.data.pagination.totalPosts || 0;
    }

    return 0;
  } catch (error) {
    console.warn(
      `⚠️ Error fetching blog posts count for locale "${locale}":`,
      error instanceof Error ? error.message : String(error)
    );
    return 0;
  }
}

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ locale: string }> }
) {
  const params = await context.params;
  const { locale } = params;

  // Validate locale dynamically using centralized config
  if (!isSupportedLocale(locale)) {
    return new NextResponse("Invalid locale", { status: 400 });
  }

  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://flowxtra.com";
  const postsPerFile = 100; // 100 items per sitemap file

  // Build HTML page (Yoast SEO style) for this locale
  let html = `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XML Sitemap Index - ${locale.toUpperCase()} - Flowxtra</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px 20px;
      background-color: #fff;
    }
    h1 {
      font-size: 32px;
      font-weight: 600;
      color: #1a1a1a;
      margin-bottom: 10px;
    }
    .description {
      color: #666;
      margin-bottom: 30px;
      font-size: 14px;
    }
    .description a {
      color: #d63638;
      text-decoration: none;
    }
    .description a:hover {
      text-decoration: underline;
    }
    .count {
      font-size: 16px;
      color: #555;
      margin-bottom: 30px;
      padding: 15px;
      background-color: #f5f5f5;
      border-radius: 4px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
      background-color: #fff;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    thead {
      background-color: #f8f9fa;
    }
    th {
      text-align: left;
      padding: 15px;
      font-weight: 600;
      color: #1a1a1a;
      border-bottom: 2px solid #e0e0e0;
      font-size: 14px;
    }
    td {
      padding: 15px;
      border-bottom: 1px solid #e0e0e0;
      font-size: 14px;
    }
    tr:hover {
      background-color: #f8f9fa;
    }
    a {
      color: #0073aa;
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
      color: #005177;
    }
    .lastmod {
      color: #666;
      font-size: 13px;
    }
  </style>
</head>
<body>
  <h1>XML Sitemap - ${locale.toUpperCase()}</h1>
  <div class="description">
    Generated by <a href="https://flowxtra.com" target="_blank">Flowxtra</a>, this is an XML Sitemap Index for ${locale.toUpperCase()}, meant for consumption by search engines.<br>
    You can find more information about XML sitemaps on <a href="https://www.sitemaps.org/" target="_blank">sitemaps.org</a>.
  </div>`;

  // Collect all sitemaps for this locale
  const sitemaps: Array<{ url: string; lastmod: string; type: string }> = [];

  // Add static pages sitemap for this locale
  sitemaps.push({
    url: `${baseUrl}/sitemap-static-${locale}.xml`,
    lastmod: new Date().toISOString(),
    type: `Static Pages`,
  });

  // Add blog sitemaps for this locale (if available)
  const totalPosts = await getBlogPostsCount(locale);
  const totalBlogFiles = Math.ceil(totalPosts / postsPerFile);

  if (totalPosts > 0 && totalBlogFiles > 0) {
    for (let fileIndex = 0; fileIndex < totalBlogFiles; fileIndex++) {
      sitemaps.push({
        url: `${baseUrl}/sitemap-${locale}-blog-${fileIndex}.xml`,
        lastmod: new Date().toISOString(),
        type: `Blog Posts`,
      });
    }
    console.log(
      `📝 Adding ${totalBlogFiles} blog sitemap file(s) for locale "${locale}" (${totalPosts} posts total)`
    );
  }

  // Add app-store sitemaps for this locale (if available)
  const totalApps = await getAppsCount(locale);
  const totalAppFiles = Math.ceil(totalApps / postsPerFile);

  if (totalApps > 0 && totalAppFiles > 0) {
    for (let fileIndex = 0; fileIndex < totalAppFiles; fileIndex++) {
      sitemaps.push({
        url: `${baseUrl}/sitemap-${locale}-app-store-${fileIndex}.xml`,
        lastmod: new Date().toISOString(),
        type: `App Store`,
      });
    }
    console.log(
      `📱 Adding ${totalAppFiles} app-store sitemap file(s) for locale "${locale}" (${totalApps} apps total)`
    );
  }

  // Display count
  html += `
  <div class="count">
    This XML Sitemap Index file contains <strong>${
      sitemaps.length
    }</strong> sitemap${sitemaps.length !== 1 ? "s" : ""}.
  </div>`;

  // Display table
  html += `
  <table>
    <thead>
      <tr>
        <th>Sitemap</th>
        <th>Type</th>
        <th>Last Modified</th>
      </tr>
    </thead>
    <tbody>`;

  sitemaps.forEach((sitemap) => {
    const lastModDate = new Date(sitemap.lastmod);
    const formattedDate =
      lastModDate.toISOString().replace("T", " ").substring(0, 19) + " +00:00";

    html += `
      <tr>
        <td><a href="${sitemap.url}" target="_blank">${sitemap.url}</a></td>
        <td>${sitemap.type}</td>
        <td class="lastmod">${formattedDate}</td>
      </tr>`;
  });

  html += `
    </tbody>
  </table>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
